# Generated by Django 5.0.6 on 2024-06-04 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_final', models.FloatField()),
                ('detalles', models.TextField()),
                ('tipo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA_CREDITO', 'Tarjeta de crédito'), ('TARJETA_DEBITO', 'Tarjeta de débito')], max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('tipo_habitacion', models.CharField(choices=[('SUITE', 'Suite'), ('DOBLE', 'Doble'), ('SENCILLA', 'Sencilla')], max_length=10)),
                ('estado', models.BooleanField()),
                ('precio', models.FloatField()),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='Facturacion.factura')),
            ],
        ),
    ]
