# Generated by Django 5.0.6 on 2024-06-04 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('numero_identificacion', models.CharField(max_length=10)),
                ('puesto', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_habitacion', models.CharField(max_length=20)),
                ('tiempo_hospedaje', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.cliente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.personal')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.reserva')),
            ],
        ),
    ]
