# Generated by Django 5.0.6 on 2024-06-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0002_remove_reserva_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
    ]
