# Generated by Django 5.0.6 on 2024-06-05 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPersonas', '0003_remove_cliente_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='reserva',
        ),
        migrations.AddField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='checkin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.checkin'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='checkout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionPersonas.checkout'),
        ),
    ]
