# Generated by Django 5.0.6 on 2024-06-04 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('LIMPIEZA', 'Limpieza'), ('COCINA', 'Cocina'), ('LAVANDERIA', 'Lavanderia'), ('CONDUCTOR', 'Conductor'), ('SEGURIDAD', 'Seguridad'), ('MASAJISTA', 'Masajista'), ('ENCARGADOPISCINA', 'Encargadopiscina'), ('RECEPCIONISTA', 'Recepcionista')], max_length=20)),
                ('turno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contratar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hojaVida', models.TextField()),
                ('terminosCondiciones', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionarEmpleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='GestionarEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionarEmpleado.administrador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionarEmpleado.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='empleados',
            field=models.ManyToManyField(through='GestionarEmpleado.GestionarEmpleado', to='GestionarEmpleado.empleado'),
        ),
    ]
